version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: angular-client # specify the directory of the Dockerfile
    #image: worldoflinux/mean-docker_angular:latest
    container_name: angular-client
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./angular-client:/app

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    #image: worldoflinux/mean-docker_express:latest
    container_name: express-server
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    container_name: mongo-angular
    volumes: 
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017" # specify port forewarding


         
         
